Test:DEMO
			
# Replace the .c and .o file names which you wish to run
 
DEMO:BcRtMt.o
#	gcc -o DEMO BcRtMt.o ../libApoorva31Rts-4NodeDDCDll.a
	gcc -o DEMO BcRtMt.o ../libApoorva31Rts_4NodeDll.a
##-L. -lPci1553Dll
BcRtMt.o:      BcRtMt.c
	gcc -g -c BcRtMt.c -o BcRtMt.o
clean:
	rm -rf *.o DEMO	
	echo "This is 1553 Single Node Sample Program"




	
