#define MAJOR_NUM_CARD1_DDC 254
#include <linux/ioctl.h>


#define DEVICE_NAME "ZACL"

/*typedef struct _Addr
{
	unsigned int Addr;
	unsigned short Data;
}Addr;*/

#define IOCTL_WRITE_PORT  _IOR(MAJOR_NUM_CARD1_DDC,0,int)
#define IOCTL_WRITE_VALUE _IOR(MAJOR_NUM_CARD1_DDC,1,int)
#define IOCTL_READ_PORT   _IOR(MAJOR_NUM_CARD1_DDC,2,int)
#define IOCTL_SET_ICS_REG _IOR(MAJOR_NUM_CARD1_DDC,3,int)
#define IOCTL_CLEAR_INTR  _IOR(MAJOR_NUM_CARD1_DDC,4,int)
#define IOCTL_GET_M1CNT   _IOR(MAJOR_NUM_CARD1_DDC,5,int)
#define IOCTL_GET_M2CNT   _IOR(MAJOR_NUM_CARD1_DDC,6,int)
#define IOCTL_GET_M3CNT   _IOR(MAJOR_NUM_CARD1_DDC,7,int)
#define IOCTL_SET_M1CNT   _IOR(MAJOR_NUM_CARD1_DDC,8,int)
#define IOCTL_SET_M2CNT   _IOR(MAJOR_NUM_CARD1_DDC,9,int)
#define IOCTL_SET_M3CNT   _IOR(MAJOR_NUM_CARD1_DDC,10,int)

#define IOCTL_MEM_READ_MODULE 	_IOR(MAJOR_NUM_CARD1_DDC,11,int)
#define IOCTL_MEM_WRITE_MODULE	_IOW(MAJOR_NUM_CARD1_DDC,12,int)



/*extern int MajorNo;

#define MAJOR_NUM_CARD1 254

#define DEVICE_NAME "ZACL"

#define IOCTL_WRITE_PORT   _IOR(MAJOR_NUM_CARD1,0,int)
#define IOCTL_WRITE_VALUE  _IOR(MAJOR_NUM_CARD1,1,int)
#define IOCTL_READ_PORT    _IOR(MAJOR_NUM_CARD1,2,int)
#define IOCTL_SET_ICS_REG  _IOR(MAJOR_NUM_CARD1,3,int)
#define IOCTL_CLEAR_INTR   _IOR(MAJOR_NUM_CARD1,4,int)
#define IOCTL_GET_M1CNT    _IOR(MAJOR_NUM_CARD1,5,int)
#define IOCTL_GET_M2CNT    _IOR(MAJOR_NUM_CARD1,6,int)
#define IOCTL_GET_M3CNT    _IOR(MAJOR_NUM_CARD1,7,int)
#define IOCTL_SET_M1CNT    _IOR(MAJOR_NUM_CARD1,8,int)
#define IOCTL_SET_M2CNT    _IOR(MAJOR_NUM_CARD1,9,int)
#define IOCTL_SET_M3CNT    _IOR(MAJOR_NUM_CARD1,10,int)


#define IOCTL_MEM_READ_MODULE 	_IOR(MAJOR_NUM_CARD1,11,int)
#define IOCTL_MEM_WRITE_MODULE	_IOW(MAJOR_NUM_CARD1,12,int)*/
