
/*++

    (C) 2004, Apollo Computing Laboratories (P) Ltd.  All rights reserved.

	NO PART  OF  THIS  PROGRAM OR PUBLICATION MAY BE REPRODUCED, TRANSMITTED,
	TRANSCRIBED, STORED IN A RETRIEVAL  SYSTEM,  OR  TRANSLATED	INTO ANY
	LANGUAGE OR COMPUTER LANGUAGE IN ANY FORM OR BY ANY MEANS, ELECTRONIC,
	MECHANICAL, MAGNETIC, OPTICAL, CHEMICAL, MANUAL, OR OTHERWISE,
	WITHOUT THE PRIOR WRITTEN PERMISSION OF :
                                                  
			APOLLO COMPUTING LABORATORIES (P) LTD.
                                                  
            12-13-197/403-405,Pavani Anasuya Tower,
                                                   
            Tarnaka, Hyderabad - 500 017. INDIA.   
                                                   
            E-mail : mktg@apollocomputing.com  



Module Name:

    Pcmcia1553.h

Abstract:

    Defines IOCTL's and Class GUID

Author:

     Mahender Reddy G.   Jan 7 2004


Environment:

    Windows - 2000/XP


Revision History:

    	
	Added MT Cmd Stack and Data Stack IOCTL's		Dec 25 2006
    
--*/




// Define an Interface Guid for Apoorva device class.
// This GUID is used to register (IoRegisterDeviceInterface) 
// an instance of an interface so that user application 
// can control the Apoorva device.
//

DEFINE_GUID (GUID_DEVINTERFACE_APOORVA, 
		0x643e59f2, 0xa018, 0x432c, 0x87, 0xc3, 0x9b, 0xfc, 0x93, 0xb5, 0xbe, 0xdc); 



#define IOCTL_PCMCIA_READ_PORT_UCHAR \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_PCMCIA_READ_PORT_USHORT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_PCMCIA_READ_PORT_ULONG \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_PCMCIA_WRITE_PORT_UCHAR \
    CTL_CODE(FILE_DEVICE_UNKNOWN,  0x910, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_PCMCIA_WRITE_PORT_USHORT \
    CTL_CODE(FILE_DEVICE_UNKNOWN,  0x911, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_PCMCIA_WRITE_PORT_ULONG \
    CTL_CODE(FILE_DEVICE_UNKNOWN,  0x912, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_MAPMEM_MAP_USER_PHYSICAL_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN,  0x913, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ATTR_MAPMEM_MAP_USER_PHYSICAL_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN,  0x914, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_READ_PORT_UCHAR180 \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x915, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_PCMCIA_WRITE_PORT_UCHAR180 \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x916, METHOD_BUFFERED, FILE_WRITE_ACCESS )

#define IOCTL_PCMCIA_SET_BCEOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x91b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_BCEOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x91e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_MTEOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x91f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_MTEOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x920, METHOD_BUFFERED, FILE_ANY_ACCESS)

/************** SET		******************/

#define IOCTL_PCMCIA_SET_RT0EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x921, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT1EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x922, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT2EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x923, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT3EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x924, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT4EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x925, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT5EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x926, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT6EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x927, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT7EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x928, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT8EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x929, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT9EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT10EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT11EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT12EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT13EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT14EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x92f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT15EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x930, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT16EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x931, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT17EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x932, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT18EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x933, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT19EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x934, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT20EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x935, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT21EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x936, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT22EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x937, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT23EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x938, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT24EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x939, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT25EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT26EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT27EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT28EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT29EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT30EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x93f, METHOD_BUFFERED, FILE_ANY_ACCESS)

/************SET OVER	********************/

#define IOCTL_PCMCIA_GET_RT0EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x940, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT1EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x941, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT2EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x942, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT3EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x943, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT4EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x944, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT5EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x945, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT6EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x946, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT7EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x947, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT8EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x948, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT9EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x949, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT10EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT11EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT12EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT13EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT14EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT15EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x94f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT16EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x950, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT17EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x951, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT18EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x952, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT19EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x953, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT20EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x954, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT21EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x955, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT22EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x956, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT23EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x957, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT24EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x958, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT25EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x959, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT26EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x95a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT27EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x95b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT28EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x95c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT29EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x95d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT30EOM_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x95f, METHOD_BUFFERED, FILE_ANY_ACCESS)

/*************** GET OVER	*******************/

#define IOCTL_PCMCIA_SET_RT0CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x960, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT1CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x961, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT2CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x962, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT3CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x963, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT4CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x964, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT5CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x965, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT6CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x966, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT7CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x967, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT8CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x968, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT9CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x969, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT10CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT11CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT12CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT13CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT14CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT15CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x96f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT16CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x970, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT17CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x971, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT18CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x972, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT19CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x973, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT20CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x974, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT21CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x975, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT22CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x976, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT23CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x977, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT24CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x978, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT25CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x979, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT26CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT27CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT28CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT29CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RT30CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97e, METHOD_BUFFERED, FILE_ANY_ACCESS)

/************* SET OVER		********************************/

#define IOCTL_PCMCIA_GET_RT0CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x97f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT1CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x980, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT2CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x981, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT3CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x982, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT4CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x983, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT5CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x984, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT6CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x985, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT7CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x986, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT8CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x987, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT9CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x988, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT10CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x989, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT11CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT12CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT13CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT14CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98d, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT15CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT16CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x98f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT17CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x990, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT18CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x991, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT19CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x992, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT20CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x993, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT21CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x994, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT22CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x995, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT23CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x996, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT24CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x997, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT25CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x998, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT26CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x999, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT27CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99a, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT28CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99b, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT29CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99c, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RT30CIRC_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99d, METHOD_BUFFERED, FILE_ANY_ACCESS)

////////////////////////////  Timers  /////////////////////////////////////////

#define IOCTL_PCMCIA_SET_RTC1_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99e, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RTC1_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x99f, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RTC2_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a0, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RTC2_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RTC3_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RTC3_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_RTDBCA_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a4, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_RTDBCA_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a5, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_CARD_EVENT_TIMER \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a6, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_MOD_EVENT_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a7, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IO_PCMCIA_REFERENCE_EVENT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a8, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_ENDOF_FRAME_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9a9, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_ENDOF_FRAME_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9aa, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_MT_TTR_ROLL_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9ab, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_MT_TTR_ROLL_COUNT \
    CTL_CODE( FILE_DEVICE_UNKNOWN, 0x9ac, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_MT_CMDSTK_ROLL_COUNT  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x9ad,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_MT_CMDSTK_ROLL_COUNT  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x9ae,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_GET_MT_DATASTK_ROLL_COUNT  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x9af,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_PCMCIA_SET_MT_DATASTK_ROLL_COUNT  \
    CTL_CODE(FILE_DEVICE_UNKNOWN,0x9b0,METHOD_BUFFERED,FILE_ANY_ACCESS)


typedef struct  _PCMCIA_WRITE_INPUT {
    ULONG   PortNumber;     // Port # to write to
    union   {               // Data to be output to port
				ULONG   LongData;
				USHORT  ShortData;
				UCHAR   CharData;
			};
}PCMCIA_WRITE_INPUT;

