Test:DEMO
			
# Replace the .c and .o file names which you wish to run
 
DEMO:ATest3B.o
#	gcc -o DEMO ATest3B.o ../libApoorva31Rts-4NodeDDCDll.a
	gcc -o DEMO ATest3B.o ../libApoorva31Rts_4NodeDll.a
##-L. -lPci1553Dll
Bctort.o:      ATest3B.c
	gcc -g -c ATest3B.c -o ATest3B.o
clean:
	rm -rf *.o DEMO	
	echo "This is 1553 Single Node Sample Program"




	
