Test:DEMO
			
# Replace the .c and .o file names which you wish to run
 
DEMO:BcMt.o
#	gcc -o DEMO BcMt.o ../libApoorva31Rts-4NodeDDCDll.a
	gcc -o DEMO BcMt.o ../libApoorva31Rts_4NodeDll.a
##-L. -lPci1553Dll
BcMt.o:      BcMt.c
	gcc -g -c BcMt.c -o BcMt.o
clean:
	rm -rf *.o DEMO	
	echo "This is 1553 Single Node Sample Program"




	
