#include <linux/ioctl.h>
#include <asm/ioctl.h>

typedef struct _Addr
{
	unsigned int Addr;
	unsigned short Data;
}Addr;


#define MAJOR_NUM_CARD1 1553
#define MAJOR_NUM_CARD2 2553
#define MAJOR_NUM_CARD3 3553
#define MAJOR_NUM_CARD4 4553
#define DEVICE_NAME "APOORVA1553"


#define IOCTL_CARD1_WRITE_PORT    _IOR(MAJOR_NUM_CARD1,0,int)
#define IOCTL_CARD1_WRITE_VALUE   _IOR(MAJOR_NUM_CARD1,1,int)
#define IOCTL_CARD1_READ_PORT     _IOR(MAJOR_NUM_CARD1,2,int)
#define IOCTL_CARD1_SET_ICS_REG   _IOR(MAJOR_NUM_CARD1,3,int)

#define IOCTL_CARD1_SOFTWARE_RESET   _IOR(MAJOR_NUM_CARD1,4,int)
#define IOCTL_CARD2_SOFTWARE_RESET   _IOR(MAJOR_NUM_CARD2,4,int)
#define IOCTL_CARD3_SOFTWARE_RESET   _IOR(MAJOR_NUM_CARD3,4,int)
#define IOCTL_CARD4_SOFTWARE_RESET   _IOR(MAJOR_NUM_CARD4,4,int)

#define IOCTL_CARD1_MOD1_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD1,10,int)
#define IOCTL_CARD1_MOD2_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD1,11,int)
 
#define IOCTL_CARD1_MOD1_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD1,14,int)
#define IOCTL_CARD1_MOD2_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD1,15,int)
 
#define IOCTL_CARD1_MOD1_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD1,18,int)
#define IOCTL_CARD1_MOD2_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD1,19,int)
 
#define IOCTL_CARD1_MOD1_GET_RTCIRC    _IOR(MAJOR_NUM_CARD1,22,int)
#define IOCTL_CARD1_MOD2_GET_RTCIRC    _IOR(MAJOR_NUM_CARD1,23,int)
 
#define IOCTL_CARD1_MOD1_GET_RTDBCA    _IOR(MAJOR_NUM_CARD1,26,int)
#define IOCTL_CARD1_MOD2_GET_RTDBCA    _IOR(MAJOR_NUM_CARD1,27,int)

#define IOCTL_CARD1_GET_RTC1      _IOR(MAJOR_NUM_CARD1,30,int)
#define IOCTL_CARD1_GET_RTC2      _IOR(MAJOR_NUM_CARD1,31,int)
#define IOCTL_CARD1_GET_RTC3      _IOR(MAJOR_NUM_CARD1,32,int)


#define IOCTL_CARD1_MOD1_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD1,33,int)
#define IOCTL_CARD1_MOD2_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD1,34,int)

#define IOCTL_CARD1_MOD1_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD1,37,int)
#define IOCTL_CARD1_MOD2_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD1,38,int)

#define IOCTL_CARD1_MOD1_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD1,41,int)
#define IOCTL_CARD1_MOD2_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD1,42,int)

#define IOCTL_CARD1_MOD1_SET_RTCIRC    _IOR(MAJOR_NUM_CARD1,45,int)
#define IOCTL_CARD1_MOD2_SET_RTCIRC    _IOR(MAJOR_NUM_CARD1,46,int)

#define IOCTL_CARD1_MOD1_SET_RTDBCA    _IOR(MAJOR_NUM_CARD1,49,int)
#define IOCTL_CARD1_MOD2_SET_RTDBCA    _IOR(MAJOR_NUM_CARD1,50,int)

#define IOCTL_CARD1_SET_RTC1      _IOR(MAJOR_NUM_CARD1,53,int)
#define IOCTL_CARD1_SET_RTC2      _IOR(MAJOR_NUM_CARD1,54,int)
#define IOCTL_CARD1_SET_RTC3      _IOR(MAJOR_NUM_CARD1,55,int)

#define IOCTL_CARD1_MOD1_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD1,56,int)
#define IOCTL_CARD1_MOD2_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD1,57,int)

#define IOCTL_CARD1_MOD1_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD1,60,int)
#define IOCTL_CARD1_MOD2_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD1,61,int)

#define IOCTL_CARD1_MOD1_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD1,64,int)
#define IOCTL_CARD1_MOD2_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD1,65,int)

#define IOCTL_CARD1_MOD1_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD1,68,int)
#define IOCTL_CARD1_MOD2_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD1,69,int)



#define IOCTL_CARD2_WRITE_PORT    _IOR(MAJOR_NUM_CARD2,0,int)
#define IOCTL_CARD2_WRITE_VALUE   _IOR(MAJOR_NUM_CARD2,1,int)
#define IOCTL_CARD2_READ_PORT     _IOR(MAJOR_NUM_CARD2,2,int)
#define IOCTL_CARD2_SET_ICS_REG   _IOR(MAJOR_NUM_CARD2,3,int)

#define IOCTL_CARD2_MOD1_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD2,10,int)
#define IOCTL_CARD2_MOD2_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD2,11,int)

#define IOCTL_CARD2_MOD1_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD2,14,int)
#define IOCTL_CARD2_MOD2_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD2,15,int)

#define IOCTL_CARD2_MOD1_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD2,18,int)
#define IOCTL_CARD2_MOD2_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD2,19,int)

#define IOCTL_CARD2_MOD1_GET_RTCIRC    _IOR(MAJOR_NUM_CARD2,22,int)
#define IOCTL_CARD2_MOD2_GET_RTCIRC    _IOR(MAJOR_NUM_CARD2,23,int)

#define IOCTL_CARD2_MOD1_GET_RTDBCA    _IOR(MAJOR_NUM_CARD2,26,int)
#define IOCTL_CARD2_MOD2_GET_RTDBCA    _IOR(MAJOR_NUM_CARD2,27,int)

#define IOCTL_CARD2_GET_RTC1      _IOR(MAJOR_NUM_CARD2,30,int)
#define IOCTL_CARD2_GET_RTC2      _IOR(MAJOR_NUM_CARD2,31,int)
#define IOCTL_CARD2_GET_RTC3      _IOR(MAJOR_NUM_CARD2,32,int)


#define IOCTL_CARD2_MOD1_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD2,33,int)
#define IOCTL_CARD2_MOD2_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD2,34,int)

#define IOCTL_CARD2_MOD1_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD2,37,int)
#define IOCTL_CARD2_MOD2_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD2,38,int)

#define IOCTL_CARD2_MOD1_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD2,41,int)
#define IOCTL_CARD2_MOD2_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD2,42,int)

#define IOCTL_CARD2_MOD1_SET_RTCIRC    _IOR(MAJOR_NUM_CARD2,45,int)
#define IOCTL_CARD2_MOD2_SET_RTCIRC    _IOR(MAJOR_NUM_CARD2,46,int)

#define IOCTL_CARD2_MOD1_SET_RTDBCA    _IOR(MAJOR_NUM_CARD2,49,int)
#define IOCTL_CARD2_MOD2_SET_RTDBCA    _IOR(MAJOR_NUM_CARD2,50,int)

#define IOCTL_CARD2_SET_RTC1      _IOR(MAJOR_NUM_CARD2,53,int)
#define IOCTL_CARD2_SET_RTC2      _IOR(MAJOR_NUM_CARD2,54,int)
#define IOCTL_CARD2_SET_RTC3      _IOR(MAJOR_NUM_CARD2,55,int)

#define IOCTL_CARD2_MOD1_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD2,56,int)
#define IOCTL_CARD2_MOD2_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD2,57,int)

#define IOCTL_CARD2_MOD1_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD2,60,int)
#define IOCTL_CARD2_MOD2_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD2,61,int)

#define IOCTL_CARD2_MOD1_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD2,64,int)
#define IOCTL_CARD2_MOD2_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD2,65,int)

#define IOCTL_CARD2_MOD1_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD2,68,int)
#define IOCTL_CARD2_MOD2_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD2,69,int)


#define IOCTL_CARD3_WRITE_PORT    _IOR(MAJOR_NUM_CARD3,0,int)
#define IOCTL_CARD3_WRITE_VALUE   _IOR(MAJOR_NUM_CARD3,1,int)
#define IOCTL_CARD3_READ_PORT     _IOR(MAJOR_NUM_CARD3,2,int)
#define IOCTL_CARD3_SET_ICS_REG   _IOR(MAJOR_NUM_CARD3,3,int)

#define IOCTL_CARD3_MOD1_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD3,10,int)
#define IOCTL_CARD3_MOD2_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD3,11,int)

#define IOCTL_CARD3_MOD1_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD3,14,int)
#define IOCTL_CARD3_MOD2_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD3,15,int)

#define IOCTL_CARD3_MOD1_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD3,18,int)
#define IOCTL_CARD3_MOD2_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD3,19,int)

#define IOCTL_CARD3_MOD1_GET_RTCIRC    _IOR(MAJOR_NUM_CARD3,22,int)
#define IOCTL_CARD3_MOD2_GET_RTCIRC    _IOR(MAJOR_NUM_CARD3,23,int)

#define IOCTL_CARD3_MOD1_GET_RTDBCA    _IOR(MAJOR_NUM_CARD3,26,int)
#define IOCTL_CARD3_MOD2_GET_RTDBCA    _IOR(MAJOR_NUM_CARD3,27,int)

#define IOCTL_CARD3_GET_RTC1      _IOR(MAJOR_NUM_CARD3,30,int)
#define IOCTL_CARD3_GET_RTC2      _IOR(MAJOR_NUM_CARD3,31,int)
#define IOCTL_CARD3_GET_RTC3      _IOR(MAJOR_NUM_CARD3,32,int)


#define IOCTL_CARD3_MOD1_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD3,33,int)
#define IOCTL_CARD3_MOD2_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD3,34,int)

#define IOCTL_CARD3_MOD1_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD3,37,int)
#define IOCTL_CARD3_MOD2_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD3,38,int)

#define IOCTL_CARD3_MOD1_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD3,41,int)
#define IOCTL_CARD3_MOD2_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD3,42,int)

#define IOCTL_CARD3_MOD1_SET_RTCIRC    _IOR(MAJOR_NUM_CARD3,45,int)
#define IOCTL_CARD3_MOD2_SET_RTCIRC    _IOR(MAJOR_NUM_CARD3,46,int)

#define IOCTL_CARD3_MOD1_SET_RTDBCA    _IOR(MAJOR_NUM_CARD3,49,int)
#define IOCTL_CARD3_MOD2_SET_RTDBCA    _IOR(MAJOR_NUM_CARD3,50,int)

#define IOCTL_CARD3_SET_RTC1      _IOR(MAJOR_NUM_CARD3,53,int)
#define IOCTL_CARD3_SET_RTC2      _IOR(MAJOR_NUM_CARD3,54,int)
#define IOCTL_CARD3_SET_RTC3      _IOR(MAJOR_NUM_CARD3,55,int)

#define IOCTL_CARD3_MOD1_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD3,56,int)
#define IOCTL_CARD3_MOD2_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD3,57,int)

#define IOCTL_CARD3_MOD1_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD3,60,int)
#define IOCTL_CARD3_MOD2_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD3,61,int)

#define IOCTL_CARD3_MOD1_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD3,64,int)
#define IOCTL_CARD3_MOD2_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD3,65,int)

#define IOCTL_CARD3_MOD1_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD3,68,int)
#define IOCTL_CARD3_MOD2_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD3,69,int)


#define IOCTL_CARD4_WRITE_PORT    _IOR(MAJOR_NUM_CARD4,0,int)
#define IOCTL_CARD4_WRITE_VALUE   _IOR(MAJOR_NUM_CARD4,1,int)
#define IOCTL_CARD4_READ_PORT     _IOR(MAJOR_NUM_CARD4,2,int)
#define IOCTL_CARD4_SET_ICS_REG   _IOR(MAJOR_NUM_CARD4,3,int)

#define IOCTL_CARD4_MOD1_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD4,10,int)
#define IOCTL_CARD4_MOD2_GET_BCEOMCNT  _IOR(MAJOR_NUM_CARD4,11,int)

#define IOCTL_CARD4_MOD1_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD4,14,int)
#define IOCTL_CARD4_MOD2_GET_MTEOMCNT  _IOR(MAJOR_NUM_CARD4,15,int)

#define IOCTL_CARD4_MOD1_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD4,18,int)
#define IOCTL_CARD4_MOD2_GET_RTEOMCNT  _IOR(MAJOR_NUM_CARD4,19,int)

#define IOCTL_CARD4_MOD1_GET_RTCIRC    _IOR(MAJOR_NUM_CARD4,22,int)
#define IOCTL_CARD4_MOD2_GET_RTCIRC    _IOR(MAJOR_NUM_CARD4,23,int)

#define IOCTL_CARD4_MOD1_GET_RTDBCA    _IOR(MAJOR_NUM_CARD4,26,int)
#define IOCTL_CARD4_MOD2_GET_RTDBCA    _IOR(MAJOR_NUM_CARD4,27,int)

#define IOCTL_CARD4_GET_RTC1      _IOR(MAJOR_NUM_CARD4,30,int)
#define IOCTL_CARD4_GET_RTC2      _IOR(MAJOR_NUM_CARD4,31,int)
#define IOCTL_CARD4_GET_RTC3      _IOR(MAJOR_NUM_CARD4,32,int)

#define IOCTL_CARD4_MOD1_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD4,33,int)
#define IOCTL_CARD4_MOD2_SET_BCEOMCNT  _IOR(MAJOR_NUM_CARD4,34,int)

#define IOCTL_CARD4_MOD1_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD4,37,int)
#define IOCTL_CARD4_MOD2_SET_MTEOMCNT  _IOR(MAJOR_NUM_CARD4,38,int)

#define IOCTL_CARD4_MOD1_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD4,41,int)
#define IOCTL_CARD4_MOD2_SET_RTEOMCNT  _IOR(MAJOR_NUM_CARD4,42,int)

#define IOCTL_CARD4_MOD1_SET_RTCIRC    _IOR(MAJOR_NUM_CARD4,45,int)
#define IOCTL_CARD4_MOD2_SET_RTCIRC    _IOR(MAJOR_NUM_CARD4,46,int)

#define IOCTL_CARD4_MOD1_SET_RTDBCA    _IOR(MAJOR_NUM_CARD4,49,int)
#define IOCTL_CARD4_MOD2_SET_RTDBCA    _IOR(MAJOR_NUM_CARD4,50,int)

#define IOCTL_CARD4_SET_RTC1      _IOR(MAJOR_NUM_CARD4,53,int)
#define IOCTL_CARD4_SET_RTC2      _IOR(MAJOR_NUM_CARD4,54,int)
#define IOCTL_CARD4_SET_RTC3      _IOR(MAJOR_NUM_CARD4,55,int)

#define IOCTL_CARD4_MOD1_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD4,56,int)
#define IOCTL_CARD4_MOD2_GET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD4,57,int)

#define IOCTL_CARD4_MOD1_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD4,60,int)
#define IOCTL_CARD4_MOD2_GET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD4,61,int)

#define IOCTL_CARD4_MOD1_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD4,64,int)
#define IOCTL_CARD4_MOD2_SET_ENDOF_FRAME_COUNT  _IOR(MAJOR_NUM_CARD4,65,int)

#define IOCTL_CARD4_MOD1_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD4,68,int)
#define IOCTL_CARD4_MOD2_SET_MT_TTR_ROLL_COUNT  _IOR(MAJOR_NUM_CARD4,69,int)


#define IOCTL_MEM_READ_MODULE1  		_IOR(MAJOR_NUM_CARD1,72,int)
#define IOCTL_MEM_WRITE_MODULE1  		_IOW(MAJOR_NUM_CARD1,73,int)

#define IOCTL_MEM_READ_MODULE2  		_IOR(MAJOR_NUM_CARD1,74,int)
#define IOCTL_MEM_WRITE_MODULE2  		_IOW(MAJOR_NUM_CARD1,75,int)

#define IOCTL_MEM_READ_MODULE3  		_IOR(MAJOR_NUM_CARD1,76,int)
#define IOCTL_MEM_WRITE_MODULE3  		_IOW(MAJOR_NUM_CARD1,77,int)

#define IOCTL_MEM_READ_MODULE4  		_IOR(MAJOR_NUM_CARD1,78,int)
#define IOCTL_MEM_WRITE_MODULE4  		_IOW(MAJOR_NUM_CARD1,79,int)



#define IOCTL_REG_READ_MODULE1  		_IOR(MAJOR_NUM_CARD1,80,int)
#define IOCTL_REG_WRITE_MODULE1  		_IOW(MAJOR_NUM_CARD1,81,int)

#define IOCTL_REG_READ_MODULE2  		_IOR(MAJOR_NUM_CARD1,82,int)
#define IOCTL_REG_WRITE_MODULE2  		_IOW(MAJOR_NUM_CARD1,83,int)

#define IOCTL_REG_READ_MODULE3  		_IOR(MAJOR_NUM_CARD1,84,int)
#define IOCTL_REG_WRITE_MODULE3  		_IOW(MAJOR_NUM_CARD1,85,int)

#define IOCTL_REG_READ_MODULE4  		_IOR(MAJOR_NUM_CARD1,86,int)
#define IOCTL_REG_WRITE_MODULE4  		_IOW(MAJOR_NUM_CARD1,87,int)


#define IOCTL_PORT_READ_MODULE1  		_IOR(MAJOR_NUM_CARD1,88,int)
#define IOCTL_PORT_WRITE_MODULE1  		_IOW(MAJOR_NUM_CARD1,89,int)

