 /* INCLUDE FILE: MODE.H

   THIS INCLUDE FILE DEFINES THE PROPER VALUES FOR EACH MODE OF
   OPERATIION */
                
#define BC 0x044f
#define MT 0X4F4F
#define RT 0X8F8F

#define BCMT 0xC44f
#define RTMT 0XCF4F
