Test:  USER


# ==============================
# USER→ user_app.c
# ==============================
 USER: user_app.o
	gcc -o USER user_app.o ../libApoorva31Rts_4NodeDll.a

 user_app.o: user_app.c
	gcc -g -c user_app.c -o user_app.o



# ==============================
# Clean
# ==============================
clean:
	rm -rf *.o  USER
	echo "This is 1553 Single Node Sample Program"
