Test:DEMO
			
# Replace the .c and .o file names which you wish to run
 
DEMO:Fileschedulerrun.o
#	gcc -o DEMO Fileschedulerrun.o ../libApoorva31Rts-4NodeDDCDll.a
	gcc -o DEMO Fileschedulerrun.o ../libApoorva31Rts_4NodeDll.a
##-L. -lPci1553Dll
Bctort.o:      Fileschedulerrun.c
	gcc -g -c Fileschedulerrun.c -o Fileschedulerrun.o
clean:
	rm -rf *.o DEMO	
	echo "This is 1553 Single Node Sample Program"




	
